bayer_method: ''
bayer_pattern: gbrg
frame_id: /camera
frame_rate: 60.0
format7_color_coding: raw8
gain: 12.041193008422852
gamma: 1.2000000000000002
guid: 00b09d0100b748f4
use_ros_time: true
video_mode: format7_mode0